# render.yaml
# Corrected configuration for deploying the Audio Transcriber app on Render.

services:
  - type: web
    name: audio-transcriber
    env: node
    plan: free # Specifies the free instance type
    buildCommand: "npm install"
    startCommand: "node server.js"
    healthCheckPath: "/"
    aptPackages:
      - ffmpeg
    envVars:
      - key: NODE_VERSION
        value: "18.17.1" # Using a specific, stable Node.js version

